### ISSUE TITLE
Mediarouter V7 aapt failure

### ISSUE THREAD

**Issue by mosabua** [simpligility/maven-android-sdk-deployer#276]
I am getting a failure from aapt on the mediaroute at the moment. 

[INFO] ------------------------------------------------------------------------
[INFO] Building Android Compatibility Extra V7 Mediarouter Library 2.7.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven) @ compatibility-v7-mediarouter ---
[INFO]
[INFO] --- properties-maven-plugin:1.0-alpha-2:read-project-properties (default) @ compatibility-v7-mediarouter ---
[INFO]
[INFO] --- android-maven-plugin:4.0.0:generate-sources (default-generate-sources) @ compatibility-v7-mediarouter ---
[INFO] Extracting libs
[INFO] Extracting apklib compatibility-v7-appcompat...
[INFO] Generating R file for com.simpligility.android.sdk-deployer:compatibility-v7-mediarouter:apklib:2.7.0
[INFO] /Volumes/lin-data/tools/android-sdk-mac_86/extras/android/support/v7/mediarouter/res/layout/mr_media_route_controller_material_dialog_b.xml:36: error: Error: No resource found that matches the given name (at 'background' with value '?attr/selectableItemBackgroundBorderless').
[INFO]
[INFO] /Volumes/lin-data/tools/android-sdk-mac_86/extras/android/support/v7/mediarouter/res/layout/mr_media_route_controller_material_dialog_b.xml:51: error: Error: No resource found that matches the given name (at 'background' with value '?attr/colorPrimary').
[INFO]
[INFO] /Volumes/lin-data/tools/android-sdk-mac_86/extras/android/support/v7/mediarouter/res/layout/mr_media_route_controller_material_dialog_b.xml:61: error: Error: No resource found that matches the given name (at 'background' with value '?attr/selectableItemBackgroundBorderless').
[INFO]
[INFO] /Volumes/lin-data/tools/android-sdk-mac_86/extras/android/support/v7/mediarouter/res/layout/mr_media_route_controller_material_dialog_b.xml:103: error: Error: No resource found that matches the given name (at 'background' with value '?attr/selectableItemBackgroundBorderless').
[INFO]
[INFO] /Volumes/lin-data/tools/android-sdk-mac_86/extras/android/support/v7/mediarouter/res/layout/mr_media_route_controller_material_dialog_b.xml:111: error: Error: No resource found that matches the given name (at 'textColor' with value '?attr/colorAccent').
[INFO]
[INFO] /Volumes/lin-data/tools/android-sdk-mac_86/extras/android/support/v7/mediarouter/res/layout/mr_media_route_controller_material_dialog_b.xml:111: error: Error: No resource found that matches the given name (at 'background' with value '?attr/selectableItemBackgroundBorderless').
[INFO]
[ERROR] Error when generating sources.
org.apache.maven.plugin.MojoExecutionException:
	at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.generateR(GenerateSourcesMojo.java:894)
	at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.execute(GenerateSourcesMojo.java:323)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.jayway.maven.plugins.android.ExecutionException: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd /Volumes/mac-data/dev/github/simpligility/maven-android-sdk-deployer/extras/compatibility-v7-mediarouter && /Volumes/lin-data/tools/android-sdk-mac_86/build-tools/22.0.0/aapt package -m -J /Volumes/mac-data/dev/github/simpligility/maven-android-sdk-deployer/extras/compatibility-v7-mediarouter/target/generated-sources/r -f --no-crunch -M /Volumes/lin-data/tools/android-sdk-mac_86/extras/android/support/v7/mediarouter/AndroidManifest.xml -S /Volumes/lin-data/tools/android-sdk-mac_86/extras/android/support/v7/mediarouter/res -S /Volumes/mac-data/dev/github/simpligility/maven-android-sdk-deployer/extras/compatibility-v7-mediarouter/target/unpacked-libs/as_compatibility-v7-appcompat/res --auto-add-overlay -I /Volumes/lin-data/tools/android-sdk-mac_86/platforms/android-21/android.jar --output-text-symbols /Volumes/mac-data/dev/github/simpligility/maven-android-sdk-deployer/extras/compatibility-v7-mediarouter/target, Result = 1
	at com.jayway.maven.plugins.android.CommandExecutor$Factory$DefaultCommandExecutor.executeCommand(CommandExecutor.java:248)
	at com.jayway.maven.plugins.android.phase01generatesources.GenerateSourcesMojo.generateR(GenerateSourcesMojo.java:890)
	... 22 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Maven Android SDK Deployer ......................... SUCCESS [  1.167 s]
[INFO] Android Platforms .................................. SUCCESS [  0.021 s]
[INFO] Android Platform 1.5 API 3 ......................... SUCCESS [  0.435 s]
[INFO] Android Platform 1.6 API 4 ......................... SUCCESS [  0.570 s]
[INFO] Android Platform 2.1 API 7 ......................... SUCCESS [  0.161 s]
[INFO] Android Platform 2.2 API 8 ......................... SUCCESS [  0.107 s]
[INFO] Android Platform 2.3.3 API 10 ...................... SUCCESS [  0.124 s]
[INFO] Android Platform 3.0 API 11 ........................ SUCCESS [  0.131 s]
[INFO] Android Platform 3.1 API 12 ........................ SUCCESS [  0.153 s]
[INFO] Android Platform 3.2 API 13 ........................ SUCCESS [  0.082 s]
[INFO] Android Platform 4.0 API 14 ........................ SUCCESS [  0.190 s]
[INFO] Android Platform 4.0.3 API 15 ...................... SUCCESS [  0.117 s]
[INFO] Android Platform 4.1 API 16 ........................ SUCCESS [  0.095 s]
[INFO] Android Platform 4.2 API 17 ........................ SUCCESS [  4.452 s]
[INFO] Android Platform 4.3 API 18 ........................ SUCCESS [  3.416 s]
[INFO] Android Platform 4.4 API 19 ........................ SUCCESS [  2.754 s]
[INFO] Android Platform 4.4W API 20 ....................... SUCCESS [  0.234 s]
[INFO] Android Platform 5.0 API 21 ........................ SUCCESS [  0.198 s]
[INFO] Android Platform 5.1 API 22 ........................ SUCCESS [  0.243 s]
[INFO] Android Add-Ons .................................... SUCCESS [  0.009 s]
[INFO] Android Add-On Google Platform 1.5 API 3 (Maps) .... SUCCESS [  0.149 s]
[INFO] Android Add-On Google Platform 1.6 API 4 (Maps) .... SUCCESS [  0.106 s]
[INFO] Android Add-On Google Platform 2.1 API 7 (Maps) .... SUCCESS [  0.077 s]
[INFO] Android Add-On Google Platform 2.2 API 8 (Maps) .... SUCCESS [  0.027 s]
[INFO] Android Add-On Google Platform 2.3.3 API 10 (Maps and USB) SUCCESS [  0.131 s]
[INFO] Android Add-On Google Platform 3.0 API 11 (Maps) ... SUCCESS [  0.032 s]
[INFO] Android Add-On Google Platform 3.1 API 12 (Maps and USB) SUCCESS [  0.039 s]
[INFO] Android Add-On Google Platform 3.2 API 13 (Maps and USB) SUCCESS [  0.039 s]
[INFO] Android Add-On Google Platform 4.0 API 14 (Maps and USB) SUCCESS [  0.075 s]
[INFO] Android Add-On Google Platform 4.0.3 API 15 (Maps and USB) SUCCESS [  0.040 s]
[INFO] Android Add-On Google Platform 4.1 API 16 (Maps and USB) SUCCESS [  0.054 s]
[INFO] Android Add-On Google Platform 4.2 API 17 (Maps and USB) SUCCESS [  0.072 s]
[INFO] Android Add-On Google Platform 4.3 API 18 (Maps and USB) SUCCESS [  0.051 s]
[INFO] Android Add-On Google Platform 4.4 API 19 (Maps and USB) SUCCESS [  0.055 s]
[INFO] Android Add-On Google Platform 5.0 API 21 (Maps and USB) SUCCESS [  0.041 s]
[INFO] Android Add-On Google Platform 5.1 API 22 (Maps and USB) SUCCESS [  0.070 s]
[INFO] Google Glass Development Kit (GDK) API 19 .......... SUCCESS [  0.100 s]
[INFO] Android Extras ..................................... SUCCESS [  0.061 s]
[INFO] Android Compatibility Extra V4 ..................... SUCCESS [  0.134 s]
[INFO] Android Compatibility Extra V7 Gridlayout Library .. SUCCESS [  8.851 s]
[INFO] Android Compatibility Extra V7 AppCompat Library ... SUCCESS [  3.486 s]
[INFO] Android Compatibility Extra V7 Mediarouter Library . FAILURE [  1.406 s]
[INFO] Android Compatibility Extra V13 .................... SKIPPED
[INFO] Android Google Play Services Extra ................. SKIPPED
[INFO] Android Google Play Services Extra for Froyo ....... SKIPPED
[INFO] Android Google Play Licensing Extra ................ SKIPPED
[INFO] Android Extras - Apk Expansion ..................... SKIPPED
[INFO] Android Google Play APK Expansion Extra - ZIP ...... SKIPPED
[INFO] Android Google Play APK Expansion Extra - Downloader SKIPPED
[INFO] Android MultiDex ................................... SKIPPED
[INFO] Repositories ....................................... SKIPPED
[INFO] Google M2Repository ................................ SKIPPED
[INFO] Android M2Repository ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 36.397 s
[INFO] Finished at: 2015-03-11T11:09:46-07:00
[INFO] Final Memory: 39M/373M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.simpligility.maven.plugins:android-maven-plugin:4.0.0:generate-sources (default-generate-sources) on project compatibility-v7-mediarouter: MojoExecutionException: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd /Volumes/mac-data/dev/github/simpligility/maven-android-sdk-deployer/extras/compatibility-v7-mediarouter && /Volumes/lin-data/tools/android-sdk-mac_86/build-tools/22.0.0/aapt package -m -J /Volumes/mac-data/dev/github/simpligility/maven-android-sdk-deployer/extras/compatibility-v7-mediarouter/target/generated-sources/r -f --no-crunch -M /Volumes/lin-data/tools/android-sdk-mac_86/extras/android/support/v7/mediarouter/AndroidManifest.xml -S /Volumes/lin-data/tools/android-sdk-mac_86/extras/android/support/v7/mediarouter/res -S /Volumes/mac-data/dev/github/simpligility/maven-android-sdk-deployer/extras/compatibility-v7-mediarouter/target/unpacked-libs/as_compatibility-v7-appcompat/res --auto-add-overlay -I /Volumes/lin-data/tools/android-sdk-mac_86/platforms/android-21/android.jar --output-text-symbols /Volumes/mac-data/dev/github/simpligility/maven-android-sdk-deployer/extras/compatibility-v7-mediarouter/target, Result = 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

**Comment by mosabua** [comment]
Does it work for your @Shusshu ?

**Comment by Shusshu** [comment]
No problem on windows with build-tools 22

Must be a fail from the tools team with the aapt for mac os x...  like the previous fail for aapt for windows
